### ISSUE TITLE
no package called ‘RepeatObserver’

### ISSUE THREAD

**Issue by bennuru** [celphin/RepeatOBserverV1#2]
I just came across this package on Biorxiv and wanted to test it out. Not sure if it it is something with my R or somewhere along the installation it is looking for "RepeatObserver" instead of "RepeatObserverV1". The full run was giving the problem, and while troubleshooting, this error popped up with: "run_plot_chromosome_parallel(nam=nam, fname=fname, inpath=inpath, outpath=outpath, pflag=pflag, plotflag=plotflag,  writeflag=writeflag, x_cpu=x_cpu)".

**Comment by celphin** [comment]
The older private version was RepeatObserver but the most up to date version is RepeatOBserverV1. Can you try installing in R as follows?

` install.packages("devtools")

 library(devtools)

 install_github("celphin/RepeatOBserverV1") #to install the package
  # Select 1:All to install all the required packages

 library(RepeatOBserverV1) # to load the package`

**Comment by celphin** [comment]
You should be able to follow the code here just replacing with your genome and it should work: [https://github.com/celphin/RepeatOBserverV1/blob/main/Example_code/Example_test_code.R](https://github.com/celphin/RepeatOBserverV1/blob/main/Example_code/Example_test_code.R)

Please let me know if you run into any other problems.

**Comment by celphin** [comment]
I checked and realized the problem. The older private version of the code was called RepeatObserver and the new version is RepeatOBserverV1. I adjusted the library load in that function now so if you reinstall it should work. Thanks for pointing this out! Please let me know if you find any other issues. 

You can reinstall with:
```
 library(devtools)
 install_github("celphin/RepeatOBserverV1") #to install the package
 library(RepeatOBserverV1)
```
