### ISSUE TITLE
Error in checkForRemoteErrors

### ISSUE THREAD

**Issue by JChenGatersleben** [celphin/RepeatOBserverV1#3]
Dear authors of RepeatOBserverV1:

Many thanks for developing such a nice tool!
However, I have came across the following errors:

#########
Plot isochores in DNA sequences
Warning messages:
1: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 5 (<-localhost:11614)
2: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 4 (<-localhost:11614)
Error in checkForRemoteErrors(val) : 
  one node produced an error: incorrect number of dimensions
Calls: <Anonymous> ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted
Error in checkForRemoteErrors(val) : 
  one node produced an error: cannot open the connection
Calls: <Anonymous> ... clusterApply -> staticClusterApply -> checkForRemoteErrors
Execution halted
cp: cannot stat '/filer-5/agruppen/CSF/Jianyong_Chen/RepeatOBserverV1/output_chromosomes/rye_H0/Chr*/*All_spec_bp35_2000*.png': No such file or directory
cp: cannot stat '/filer-5/agruppen/CSF/Jianyong_Chen/RepeatOBserverV1/output_chromosomes/rye_H0/Chr*/histograms/*POWER_SUM*s_0.5std_1*.pdf': No such file or directory
cp: cannot stat '/filer-5/agruppen/CSF/Jianyong_Chen/RepeatOBserverV1/output_chromosomes/rye_H0/Chr*/*DNAwalk*.png': No such file or directory
cp: cannot stat '/filer-5/agruppen/CSF/Jianyong_Chen/RepeatOBserverV1/output_chromosomes/rye_H0/Chr*/rye_H0_Chr*_Shannon_plot_norm.png': No such file or directory
cp: cannot stat '/filer-5/agruppen/CSF/Jianyong_Chen/RepeatOBserverV1/output_chromosomes/rye_H0/Chr*/*roll_mean_Shannon_100.png': No such file or directory
cp: cannot stat '/filer-5/agruppen/CSF/Jianyong_Chen/RepeatOBserverV1/output_chromosomes/rye_H0/Chr*/*roll_mean_Shannon_1000.png': No such file or directory
cp: cannot stat '/filer-5/agruppen/CSF/Jianyong_Chen/RepeatOBserverV1/output_chromosomes/rye_H0/Chr*/*roll_mean_Shannon_250.png': No such file or directory
cp: cannot stat '/filer-5/agruppen/CSF/Jianyong_Chen/RepeatOBserverV1/output_chromosomes/rye_H0/Chr*/*roll_mean_Shannon_500.png': No such file or directory
rm: cannot remove 'Centromere_summary.txt': No such file or directory
cat: '/filer-5/agruppen/CSF/Jianyong_Chen/RepeatOBserverV1/output_chromosomes/rye_H0/Chr*/histograms/Centromere_*.txt': No such file or directory
rm: cannot remove 'Centromere_summary_Shannon.txt': No such file or directory
cat: '/filer-5/agruppen/CSF/Jianyong_Chen/RepeatOBserverV1/output_chromosomes/rye_H0/Chr*/*Centromere_MIN_Shannon.txt': No such file or directory
grep: Centromere_summary_Shannon_35_no_telo.txt: No such file or directory
cp: cannot stat '/filer-5/agruppen/CSF/Jianyong_Chen/RepeatOBserverV1/output_chromosomes/rye_H0/Chr*/*Shannon_div_window*.png': No such file or directory
#################

Do you have any idea what's wrong?

Greetings
JC

**Comment by celphin** [comment]
Thanks for trying it out and sending these errors. Could you post the # of cpu and memory you are trying to run it with? Are you running with a slurm scheduler? It is possibly failing because there is not enough memory. Did the chromosome parts work for you?

**Comment by JChenGatersleben** [comment]
Dear celphin:

Many thanks for your quick reply!

1. I am doing test running in slurm (CPU:2, mem: 102400 Mb):
sh Setup_Run_Repeats.sh -i rye -f test.fa -h H0 -c 2 -m 102400

2. My test chromosome size is 58 MB and largeimages.png were generated. However, in the folder Summary_output, only spectra_parts can generate result. The other folders like Shannon_div, histograms, DNAwalks they are empty.

Greetings
JC

**Comment by celphin** [comment]
I need to fix this properly in the code but for now I think it should run if you have more than one chromosome.

**Comment by celphin** [comment]
This is a reasonably small genome to test with:

```
# download the Setup_Run_Repeats.sh
wget https://raw.githubusercontent.com/celphin/RepeatOBserverV1/main/Setup_Run_Repeats.sh
chmod +x Setup_Run_Repeats.sh
dos2unix Setup_Run_Repeats.sh

# download genome
wget https://www.arabidopsis.org/download_files/Genes/Col-CEN%20genome%20assembly%20release/ColCEN.fasta

sh Setup_Run_Repeats.sh -i COLCEN -f ColCEN.fasta -h H0 -c 2 -m 102400
```

**Comment by JChenGatersleben** [comment]
Dear celphin:

Problem solved! Many thanks for your help and wish you all the best!
JC
