### ISSUE TITLE
error：need finite 'ylim' values

### ISSUE THREAD

**Issue by ransenyu** [celphin/RepeatOBserverV1#4]
Hello,

I am using RepeatObserver for centromere identification in genomic sequences. However, I've encountered an issue during the final stages of the process. The script is throwing an error related to plotting: `Error in checkForRemoteErrors(val) : one node produced an error: need finite 'ylim' values`. This error seems to be associated with the plotting function, specifically with determining the y-axis limits (`ylim`).

Here are some details about the issue:

- The error occurs in the last step of the RepeatObserver process when it tries to plot the results.
- My data seems to be in the correct format and does not contain any infinite or NaN values, as far as I can tell.
- I am running this on Ubuntu 20.04 with R version 4.1.2.

I am not sure how to address this issue. Could you please provide some guidance on what might be causing this error and how to resolve it? Any help or suggestions would be greatly appreciated.

[nohup.out.txt](https://github.com/celphin/RepeatOBserverV1/files/13991912/nohup.out.txt)

Thank you for your assistance!

Best regards,
ransenyu

**Comment by celphin** [comment]
Yes, this is an issue with plotting at the end of the script. As a short term fix, the beta version of the script should let all of your chromosomes finish except the one with the issue. I believe this issue is the result of a large gap in the chromosome with an issue but I'm not certain and can confirm once the issue is fixed. 

It should be fine to download this beta version:
```
wget https://raw.githubusercontent.com/celphin/RepeatOBserverV1/main/Setup_Run_Repeats_beta.sh
chmod +x Setup_Run_Repeats_beta.sh
dos2unix Setup_Run_Repeats_beta.sh
```
And then run just rerun the code the same way you did originally with this new script - it should restart from close to where it left off. 

Please let me know if this causes any problems. I will get back to you about the cause of the plotting issue.

**Comment by ransenyu** [comment]
> Yes, this is an issue with plotting at the end of the script. As a short term fix, the beta version of the script should let all of your chromosomes finish except the one with the issue. I believe this issue is the result of a large gap in the chromosome but I'm not certain and can confirm once the issue is fixed.
> 
> It should be fine to download this beta version:
> 
> ```
> wget https://raw.githubusercontent.com/celphin/RepeatOBserverV1/main/Setup_Run_Repeats_beta.sh
> chmod +x Setup_Run_Repeats_beta.sh
> dos2unix Setup_Run_Repeats_beta.sh
> ```
> 
> And then run just rerun the code the same way you did originally with this new script - it should restart from close to where it left off.
> 
> Please let me know if this causes any problems. I will get back to you about the cause of the plotting issue.

Thanks a bunch for the swift response and the workaround with the beta script! 

I'll download and run the beta version as per your instructions and let you know how it goes. Looking forward to any further insights you might have about the plotting issue in the meantime.

Appreciate all your help!

**Comment by celphin** [comment]
Hi again, I have updated the script to run even on very small chromosomes (~3Mbp) but chromosomes <3Mbp will not run. You can try to download the new script and run it. You will need to remove your old folders, reinstall the R library and start from scratch but it should finish now. Please let me know if you still run into any problems.

**Comment by ransenyu** [comment]
> Hi again, I have updated the script to run even on very small chromosomes (~3Mbp) but chromosomes <3Mbp will not run. You can try to download the new script and run it. You will need to remove your old folders, reinstall the R library and start from scratch but it should finish now. Please let me know if you still run into any problems.

Thanks for the update! I'll download the new script and give it a go after setting things up from scratch. I'll let you know how it turns out. Appreciate your help!

**Comment by ransenyu** [comment]
Hi ,
I recently re-ran my data using the updated version of your software and encountered a couple of issues.

Firstly, the software was unable to recognize all of my chromosomes. Based on your documentation, chromosomes should be identified if they are over 3M in size. I've verified that all of my chromosomes fall within the 4-8M range, yet two chromosomes, specifically those of 6.6M and 4.2M, were not detected. This is puzzling, and I am keen to understand why this might be happening.

Secondly, I am pleased to report that the previous errors I encountered no longer occur. However, I've run into a new issue: "Error in sd_chr_list1[, 3] : subscript out of bounds." This is followed by reports of missing files, which halts further analysis. This is a concern as it seems to disrupt the workflow significantly.
[nohup.txt](https://github.com/celphin/RepeatOBserverV1/files/14371139/nohup.txt)

For context, my genome is that of a fungus, with an approximate size of 42M. I've reviewed some of the heatmaps generated and noticed that they do not exhibit the characteristics shown in the examples provided. I am wondering if this could be due to species-specific traits that make it challenging to identify centromere positions, thereby interrupting subsequent analyses.

I am more than willing to provide my genome files and all the results from this run for your review. I believe this could aid in diagnosing the issues at hand more effectively. Your guidance on how to proceed or any adjustments I might need to make would be greatly appreciated.

**Comment by celphin** [comment]
Hi, I have not tried running the program on any fungal genomes yet. Thus I do not know that the decrease in repeat diversity (that we saw in plants and animals) will also occur at fungal centromeres. I would be keen to help you look at this though. That genome is also much smaller than any I have tried running yet. If you can provide the fasta file I can take try running it. We may need to adjust the parameters slightly for such a small genome/chromosomes. The ylim error that you got earlier was a result of small chromosomes (e.g. like the microchromosomes in birds).

**Comment by celphin** [comment]
Some fungi have point centromeres - that are only <400bp long. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6107279/
Others are regional and maybe well conserved sequences though: https://www.biorxiv.org/content/10.1101/2020.06.29.179234v1.full

**Comment by celphin** [comment]
The program has been edited so that chromosomes shorter than 5Mbp are not initially run. This allows most chromosomes to run without any window size (ylim) issues. If you have smaller chromosomes with expected point centromeres (e.g. in a fungi species), I recommend exploring the emboss CG isochore plots for regions of low CG content and high repetition. The program can also be run on these chromosomes but the final steps and some shannon diversity plots will not be made.
