### ISSUE TITLE
Clarification on output tables?

### ISSUE THREAD

**Issue by rotifergirl** [celphin/RepeatOBserverV1#5]
Hi there,

Really cool approach to this analysis and great package!

Apologies if I've overlooked some documentation, but some clarification of the summary tables would be appreciated. I'm mostly after the column names in Centromere_summary.txt and the summary files for the shannon windows. Each has obvious columns for chromosome names and species, but I also end up with two numerical columns and one is confusing. 

For example, I assume that the column with a number (e.g. 21617501 or 12501) is the predicted midpoint of the putative centromere, but there is another column where most of the numbers are expressed in scientific notation (e.g. 2.8e+07 or 3.6e+07), though some are not. What are these columns?

**Comment by celphin** [comment]
Hi, Thanks for the suggestions and sorry for the slow response. I have finally updated the package, documentation and output organization. The scientific notation was hard to remove (R automatically switches to scientific notation if there are zeros on the end of the number) but the first column is the predicted centromere position and the second column is the total chromosome length both in bp. There is no loss of information in the switch to scientific notation.
